version: '3.8'

services:

  chatgpt-client-api:
    container_name: chatgpt-client-api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './api:/app:rw'
      - '/app/node_modules/'
    depends_on:
      - chatgpt-client-db
    networks:
      - chatgpt-client-network


  chatgpt-client-db:
    container_name: chatgpt-client-db
    image: 'mongo'
    ports:
      - '27017:27017'
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    #   - MONGO_INITDB_DATABASE=chat_gpt_client
    volumes: 
      - "chatgpt-client-volume:/data/db"
    networks:
      - chatgpt-client-network
      
  


  # Utility containers
  # For example: docker-compose run --rm api-npm i -D @types/express
  api-npm:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - './api:/app:rw'
    networks:
      - chatgpt-client-network

  api-npx:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npx']
    volumes:
      - './api:/app:rw'
    networks:
      - chatgpt-client-network


volumes:
  chatgpt-client-volume:
    driver: local

networks:
 chatgpt-client-network:
   driver: bridge